column_width = 80
# indent_type = "Spaces"
indent_type = "Tabs"
indent_width = 3
quote_style = "AutoPreferSingle"
# quote_style = "AutoPreferDouble"
no_call_parentheses = false
line_endings = "Unix"
# call_parentheses = "NoSingleTable"
# call_parentheses = "NoSingleString"
call_parentheses = "Always"
# call_parentheses = "None"
collapse_simple_statement = "Always" # This makes some functions be one liners
# collapse_simple_statement = "ConditionalOnly"
# collapse_simple_statement = "Never"
# collapse_simple_statement = "FunctionOnly"

[sort_requires]
enabled = true
