require("user.launch")

spec("user.colorscheme")
spec("user.right-corner-diagnostics")

spec("user.devicons")
spec("user.treesitter")
spec("user.cmp")
spec("user.autopairs")
spec("user.comment")
spec("user.gitsigns")
spec("user.telescope")
spec("user.mason")
spec("user.lsp-config")
spec("user.project")
spec("user.null-ls")
spec("user.colorizer")
spec("user.color-converter")
spec("user.accelerated-jk")
spec("user.surround")
spec("user.harpoon")

require("user.settings")
require("user.keymaps")

require("user.lazy")
