require("user.settings")
require("user.keymaps")

require("user.launch")
spec("user.colorscheme")
spec("user.devicons")
spec("user.treesitter")
spec("user.cmp")
spec("user.gitsigns")
spec("user.telescope")
spec("user.mason")
spec("user.lspconfig")
spec("user.comment")
require("user.lazy")
