require('keymaps')
-- local user = {}

-- user = {
--   colorscheme = 'jetjbp', -- Colorscheme
--   restore = true, -- Restore session, cursor and view
--   disable_builtins = true, -- Disable builtins plugins
-- }

-- user.modules = {
--   acceleratedjk = true,
--   folds = true,
--   keymaps = true,
--   afiolb = true, -- Ask user for input if there is only one active normal buffer.
--   netrw = true,
--   notifications = true, -- Override notifications to integrate with the DE/WM
--   sdmog = true, -- Show where the . mark is in the file with an icon on the sign column(gutter).
--   skeletons = true,
--   status = true, -- Simple pure lua statusline, winbar and other indicators.
--   strict_cursor = true, -- Adds a second mode cursor.
--   virtcolumn = true, -- Replaces the default colorcolumn to one that uses virtualtext
-- }

-- user.opts = {
--   breakindent = true, -- Every wrapped line will continue visually indented
--   clipboard = 'unnamedplus', -- Clipboard mode
--   cmdheight = 0,
--   conceallevel = 2, -- Show concealed text when the cursor is not on top
--   confirm = true, -- Confirm dialogs
--   cursorcolumn = true,
--   cursorline = true,
--   diffopt = 'foldcolumn:0,hiddenoff,vertical',
--   expandtab = true, -- Convert tabs to spaces
--   grepprg = 'rg --hidden --no-heading --vimgrep', -- Grep command
--   ignorecase = true, -- Ignore case
--   inccommand = 'split', -- Shows just like nosplit, but partially off-screen
--   infercase = true,
--   joinspaces = true, -- Commands like gq or J insert two spaces on punctuation
--   lazyredraw = true, -- Lazy redraw the screen
--   list = true, -- Show non-visible characters
--   matchpairs = '(:),{:},[:],<:>,=:;', -- Match pairs
--   mousefocus = true, -- Focusing cursor on the window with the keyboard focus
--   number = true,
--   -- pumblend = 9, -- Transparency for the pop up menu
--   pumheight = 6, -- Amount of lines shown in completion menus
--   relativenumber = true,
--   scrolloff = 9, -- Cursor does not reach top/bottom
--   secure = true, -- Self-explanatory
--   shiftround = true, -- Round indent to multiple of "shiftwidth"
--   shortmess = 'oOstIFS', -- Style for displaying messages
--   showbreak = '↪', -- '↳' Shows when text is being wrapped
--   showmode = false, -- Show or hide the mode you are on in the status line
--   showtabline = 0, -- Show top tab bar
--   sidescrolloff = 9, -- Cursor does not reach sides
--   signcolumn = 'number', -- Column for lsp/linting errors and warnings
--   smartcase = true, -- Smart case
--   smartindent = true, -- Smart indentation
--   softtabstop = -1, -- Tab length, if negative shiftwidth value is used
--   spelllang = 'en,cjk', -- Spell check: English - PascalCase and camelCase
--   spelloptions = 'camel', -- Options for spell checking
--   spellsuggest = 'best', -- Spelling suggestions
--   splitbelow = true, -- Force splits to go below current window
--   splitright = true, -- Force vsplits to go to the right of current window
--   swapfile = false, -- It does (not) creates a swapfile
--   synmaxcol = 160, -- Column limit for syntax highlight
--   textwidth = 80, -- Delimit text blocks to N columns
--   timeoutlen = 300, -- Time given for doing a sequence
--   undofile = true, -- Persistent undo - undo after you re-open the file
--   undolevels = 6000, -- Levels of undoing
--   updatetime = 300, -- Faster completion, it's the time for CursorHold event
--   whichwrap = '<,>,[,],h,l,b,s,~', -- Jump to the next line if you reach eol
--   winblend = 9, -- Transparency for windows
--   winhighlight = 'Normal:ActiveWindow,NormalNC:InactiveWindow',
--   wrap = false, -- Wrap lines
-- }

-- return user
